"""
Mock API Server for HoYoverse — Genshin Impact Player Support Demo
Group: genshin-hoyoverse
Generated by Omilia Demo Data Generator
"""

from fastapi import FastAPI, HTTPException, Header, Query
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, HTMLResponse, PlainTextResponse
from pydantic import BaseModel, Field
from typing import Optional, List
import json
import uuid
from pathlib import Path
from datetime import datetime, timezone

# ---------------------------------------------------------------------------
# Seed data
# ---------------------------------------------------------------------------
SEED_DATA_PATH = Path(__file__).parent / "seed_data.json"
with open(SEED_DATA_PATH) as f:
    SEED_DATA = json.load(f)

API_KEY = "demo-api-key-genshin-hoyoverse"
CUSTOMER_NAME = "HoYoverse — Genshin Impact"

# ---------------------------------------------------------------------------
# Smart path probing (works in local and Docker contexts)
# ---------------------------------------------------------------------------
def _probe(*candidates: str) -> Path:
    """Return the first existing path among the candidates. Default to the first."""
    here = Path(__file__).parent
    root = here.parent
    for rel in candidates:
        p = (here / rel) if not rel.startswith("/") else Path(rel)
        if p.exists():
            return p
        p2 = root / rel
        if p2.exists():
            return p2
    return root / candidates[0]

WEBSITE_DIR = _probe("website")
DOCUMENTS_DIR = _probe("documents")
MANUAL_UPLOAD_DIR = _probe("manual_upload")
OPENAPI_DIR = _probe("server/openapi", "openapi")
CHEATSHEET_MD = _probe("DEMO_CHEATSHEET.md")

# ---------------------------------------------------------------------------
# FastAPI app
# ---------------------------------------------------------------------------
app = FastAPI(
    title=f"{CUSTOMER_NAME} — Demo API",
    description="Mock API server for the Genshin Impact player support Copilot demo.",
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ---------------------------------------------------------------------------
# Auth dependency
# ---------------------------------------------------------------------------
async def verify_api_key(x_api_key: str = Header(default=None)):
    if x_api_key and x_api_key != API_KEY:
        raise HTTPException(status_code=401, detail="Invalid API key")


def _case_insensitive_lookup(index: dict, key: str):
    """Look up by case-insensitive key match. Returns (matched_key, value) or (None, None)."""
    if key is None:
        return None, None
    target = str(key).upper()
    for k, v in index.items():
        if str(k).upper() == target:
            return k, v
    return None, None


# ---------------------------------------------------------------------------
# System endpoints
# ---------------------------------------------------------------------------
@app.get("/health", tags=["System"])
async def health():
    return {"status": "ok", "customer": CUSTOMER_NAME}


@app.get("/", include_in_schema=False)
async def serve_website():
    idx = WEBSITE_DIR / "index.html"
    if idx.exists():
        return FileResponse(idx)
    return {"message": f"{CUSTOMER_NAME} Demo API", "docs": "/docs"}


@app.get("/cheatsheet", include_in_schema=False)
@app.get("/cheatsheet.html", include_in_schema=False)
async def serve_cheatsheet():
    html_path = WEBSITE_DIR / "cheatsheet.html"
    if html_path.exists():
        return FileResponse(html_path, media_type="text/html")
    if CHEATSHEET_MD.exists():
        # Render the markdown as pre-formatted HTML (lightweight fallback)
        text = CHEATSHEET_MD.read_text(encoding="utf-8")
        html = (
            "<!doctype html><html><head><meta charset='utf-8'>"
            "<title>Demo Cheatsheet</title>"
            "<style>body{font-family:-apple-system,sans-serif;max-width:960px;"
            "margin:40px auto;padding:0 20px;color:#1C2340;background:#F5F4EC;}"
            "pre{white-space:pre-wrap;word-wrap:break-word;line-height:1.5;}"
            "h1,h2,h3{color:#4A5BCA;}</style></head><body>"
            f"<pre>{text}</pre></body></html>"
        )
        return HTMLResponse(html)
    raise HTTPException(status_code=404, detail="Cheatsheet not found")


@app.get("/documents", tags=["Documents"])
async def list_documents():
    if not DOCUMENTS_DIR.exists():
        return {"documents": []}
    files = [f.name for f in DOCUMENTS_DIR.iterdir() if f.is_file()]
    return {"documents": sorted(files)}


@app.get("/documents/{filename}", tags=["Documents"])
async def serve_document(filename: str):
    doc_path = DOCUMENTS_DIR / filename
    if not doc_path.exists():
        raise HTTPException(status_code=404, detail="Document not found")
    return FileResponse(doc_path)


@app.get("/manual_upload", tags=["Documents"])
async def list_manual_upload():
    if not MANUAL_UPLOAD_DIR.exists():
        return {"folders": []}
    folders = {}
    for folder in sorted(MANUAL_UPLOAD_DIR.iterdir()):
        if folder.is_dir():
            folders[folder.name] = [f.name for f in sorted(folder.iterdir()) if f.is_file()]
    return {"folders": folders}


@app.get("/manual_upload/{stage}/{filename}", tags=["Documents"])
async def serve_manual_upload(stage: str, filename: str):
    path = MANUAL_UPLOAD_DIR / stage / filename
    if not path.exists():
        raise HTTPException(status_code=404, detail="File not found")
    return FileResponse(path)


@app.get("/openapi-spec", tags=["Documents"])
async def serve_openapi_spec():
    yaml_path = OPENAPI_DIR / "genshin-hoyoverse_api.yaml"
    if not yaml_path.exists():
        raise HTTPException(status_code=404, detail="OpenAPI spec not found")
    return FileResponse(
        yaml_path,
        media_type="application/x-yaml",
        filename="genshin-hoyoverse_api.yaml",
    )


# ===========================================================================
# Pydantic request models
# ===========================================================================
class VerifyOwnershipRequest(BaseModel):
    uid: Optional[str] = None
    last_topup_amount_usd: Optional[float] = None
    last_topup_date: Optional[str] = None
    last_5star_pulled: Optional[str] = None
    device_model: Optional[str] = None
    adventure_rank: Optional[int] = None
    server_region: Optional[str] = None
    hoyoverse_email: Optional[str] = None


class InitiateRecoveryRequest(BaseModel):
    uid: str
    verification_method: str = Field(..., description="knowledge_based | email_otp | platform_link")
    notes: Optional[str] = None


class ResetLoginRequest(BaseModel):
    uid: str
    new_email: Optional[str] = None
    new_phone: Optional[str] = None


class RefundRequest(BaseModel):
    order_id: str
    reason: str
    is_minor_account: Optional[bool] = False


class GuardianVerificationRequest(BaseModel):
    uid: str
    guardian_name: str
    gov_id_last4: str
    child_dob: str
    payment_last4: str


class CompensationTicketRequest(BaseModel):
    uid: str
    incident_id: Optional[str] = None
    category: str = Field(..., description="outage | bug | lost_items | missing_rewards")
    description: str
    requested_primogems: Optional[int] = None


class IngameMailRequest(BaseModel):
    uid: str
    subject: str
    body: str
    attachments: Optional[List[str]] = None


# ===========================================================================
# Account Recovery endpoints
# ===========================================================================
@app.get("/api/player/search", tags=["Account Recovery"])
async def search_player(
    last_topup_amount_usd: Optional[float] = Query(None),
    last_topup_date: Optional[str] = Query(None),
    device_model: Optional[str] = Query(None),
    server_region: Optional[str] = Query(None),
    last_5star_pulled: Optional[str] = Query(None),
    adventure_rank: Optional[int] = Query(None),
    hoyoverse_email: Optional[str] = Query(None),
):
    """
    Knowledge-based player search for account recovery when the caller does not have their UID.
    Requires at least 3 matching fields to return a result (prevents false positives).
    """
    filters = {
        "last_topup_amount_usd": last_topup_amount_usd,
        "last_topup_date": last_topup_date,
        "device_model": device_model,
        "server_region": server_region,
        "last_5star_pulled": last_5star_pulled,
        "adventure_rank": adventure_rank,
        "hoyoverse_email": hoyoverse_email,
    }
    provided = {k: v for k, v in filters.items() if v is not None and v != ""}
    if len(provided) < 3:
        raise HTTPException(
            status_code=400,
            detail=(
                "Knowledge-based search requires at least 3 fields. "
                f"Provided: {len(provided)}. Available fields: {', '.join(filters.keys())}"
            ),
        )

    matches = []
    for uid, player in SEED_DATA.get("players", {}).items():
        score = 0
        for key, value in provided.items():
            pv = player.get(key)
            if pv is None:
                continue
            if isinstance(pv, str) and isinstance(value, str):
                if pv.strip().lower() == value.strip().lower():
                    score += 1
            else:
                if pv == value:
                    score += 1
        if score >= 3:
            matches.append({"uid": uid, "match_score": score, "name": player.get("name")})

    if not matches:
        raise HTTPException(
            status_code=404,
            detail="No player matched the provided criteria with confidence. Try escalating to a human agent.",
        )
    matches.sort(key=lambda m: -m["match_score"])
    return {"status": "success", "count": len(matches), "data": matches}


@app.get("/api/player/search_by_platform", tags=["Account Recovery"])
async def search_player_by_platform(
    linked_platform: str = Query(..., description="Apple | PSN | HoYoverse | Google | Xbox"),
    linked_platform_id: str = Query(..., description="Platform-specific ID / username"),
):
    """Platform-based lookup for callers who have their linked platform credentials."""
    target_platform = linked_platform.strip().lower()
    target_pid = linked_platform_id.strip().lower()
    for uid, player in SEED_DATA.get("players", {}).items():
        if (str(player.get("linked_platform", "")).lower() == target_platform
                and str(player.get("linked_platform_id", "")).lower() == target_pid):
            return {"status": "success", "data": {"uid": uid, "name": player.get("name")}}
    raise HTTPException(status_code=404, detail=f"No player found with {linked_platform} / {linked_platform_id}")


@app.get("/api/player/{uid}", tags=["Account Recovery"])
async def get_player_account(uid: str):
    """Retrieve full player account by UID."""
    _, player = _case_insensitive_lookup(SEED_DATA.get("players", {}), uid)
    if player is None:
        raise HTTPException(status_code=404, detail=f"Player {uid} not found")
    return {"status": "success", "data": player}


@app.post("/api/account/verify_ownership", tags=["Account Recovery"])
async def verify_ownership(body: VerifyOwnershipRequest):
    """
    Verify ownership of a UID by matching caller-provided knowledge-based answers
    against the stored account. Returns a match score 0-5.
    """
    if not body.uid:
        raise HTTPException(status_code=400, detail="uid is required")
    _, player = _case_insensitive_lookup(SEED_DATA.get("players", {}), body.uid)
    if player is None:
        raise HTTPException(status_code=404, detail=f"Player {body.uid} not found")

    checks = []
    score = 0
    fields = [
        ("last_topup_amount_usd", body.last_topup_amount_usd),
        ("last_topup_date", body.last_topup_date),
        ("last_5star_pulled", body.last_5star_pulled),
        ("device_model", body.device_model),
        ("adventure_rank", body.adventure_rank),
        ("server_region", body.server_region),
        ("hoyoverse_email", body.hoyoverse_email),
    ]
    for field, provided in fields:
        if provided is None:
            continue
        stored = player.get(field)
        match = False
        if stored is not None:
            if isinstance(stored, str) and isinstance(provided, str):
                match = stored.strip().lower() == provided.strip().lower()
            else:
                match = stored == provided
        checks.append({"field": field, "match": match})
        if match:
            score += 1

    verified = score >= 3
    return {
        "status": "success",
        "data": {
            "uid": body.uid,
            "verified": verified,
            "match_score": score,
            "checks": checks,
            "threshold": 3,
        },
    }


@app.post("/api/account/initiate_recovery", tags=["Account Recovery"])
async def initiate_account_recovery(body: InitiateRecoveryRequest):
    """Open a recovery ticket. Returns a recovery case ID."""
    _, player = _case_insensitive_lookup(SEED_DATA.get("players", {}), body.uid)
    if player is None:
        raise HTTPException(status_code=404, detail=f"Player {body.uid} not found")
    case_id = f"REC{uuid.uuid4().hex[:10].upper()}"
    return {
        "status": "success",
        "data": {
            "case_id": case_id,
            "uid": body.uid,
            "verification_method": body.verification_method,
            "opened_at": datetime.now(timezone.utc).isoformat(),
            "estimated_resolution_hours": 24 if body.verification_method == "knowledge_based" else 2,
            "notes": body.notes,
        },
    }


@app.post("/api/account/reset_login_method", tags=["Account Recovery"])
async def reset_login_method(body: ResetLoginRequest):
    """Reset the primary login email or phone for a verified account."""
    _, player = _case_insensitive_lookup(SEED_DATA.get("players", {}), body.uid)
    if player is None:
        raise HTTPException(status_code=404, detail=f"Player {body.uid} not found")
    if not body.new_email and not body.new_phone:
        raise HTTPException(status_code=400, detail="Provide new_email or new_phone")
    changes = {}
    if body.new_email:
        changes["hoyoverse_email"] = body.new_email
    if body.new_phone:
        changes["phone"] = body.new_phone
    return {
        "status": "success",
        "data": {
            "uid": body.uid,
            "changes_pending_verification": changes,
            "confirmation_required_window_hours": 24,
        },
    }


# ===========================================================================
# Wish and Gacha endpoints
# ===========================================================================
@app.get("/api/wishes/active_banners", tags=["Wish and Gacha"])
async def get_active_banners():
    """List current character event, weapon event, and standard banners."""
    return {
        "status": "success",
        "data": SEED_DATA.get("active_banners", []),
    }


@app.get("/api/player/{uid}/wish_history", tags=["Wish and Gacha"])
async def get_wish_history(uid: str, banner: Optional[str] = Query(None)):
    """Return wish history summary for a player, optionally filtered by banner."""
    _, player = _case_insensitive_lookup(SEED_DATA.get("players", {}), uid)
    if player is None:
        raise HTTPException(status_code=404, detail=f"Player {uid} not found")
    _, history = _case_insensitive_lookup(SEED_DATA.get("wish_history", {}), uid)
    if history is None:
        return {"status": "success", "data": {"uid": uid, "history": []}}
    if banner and banner.lower() not in str(history.get("banner", "")).lower():
        return {
            "status": "success",
            "data": {"uid": uid, "banner_requested": banner, "history": []},
        }
    return {"status": "success", "data": {"uid": uid, **history}}


@app.get("/api/player/{uid}/pity_counter", tags=["Wish and Gacha"])
async def get_pity_counter(uid: str, banner: Optional[str] = Query(None)):
    """Return current pity status on the active banner."""
    _, history = _case_insensitive_lookup(SEED_DATA.get("wish_history", {}), uid)
    if history is None:
        raise HTTPException(status_code=404, detail=f"No wish history found for {uid}")
    pulls = history.get("pulls_since_last_5star", 0)
    soft_pity = pulls >= 75
    hard_pity_in = max(0, 90 - pulls)
    return {
        "status": "success",
        "data": {
            "uid": uid,
            "banner": history.get("banner"),
            "pulls_since_last_5star": pulls,
            "soft_pity_active": soft_pity,
            "pulls_until_hard_pity": hard_pity_in,
            "soft_pity_threshold": 75,
            "hard_pity_threshold": 90,
            "note": (
                "Soft pity is active — 5-star drop rate is dramatically elevated above pull 75."
                if soft_pity else "Normal drop rates apply."
            ),
        },
    }


# ===========================================================================
# Top-Up and Refund endpoints
# ===========================================================================
@app.get("/api/orders/{order_id}", tags=["Top-Up and Refund"])
async def get_order_status(order_id: str):
    """Retrieve order by order ID."""
    _, order = _case_insensitive_lookup(SEED_DATA.get("orders", {}), order_id)
    if order is None:
        raise HTTPException(status_code=404, detail=f"Order {order_id} not found")
    return {"status": "success", "data": order}


@app.post("/api/orders/{order_id}/retry_delivery", tags=["Top-Up and Refund"])
async def retry_crystal_delivery(order_id: str):
    """Retry Genesis Crystal delivery for an order that got stuck in payment-successful / crystals-not-delivered state."""
    _, order = _case_insensitive_lookup(SEED_DATA.get("orders", {}), order_id)
    if order is None:
        raise HTTPException(status_code=404, detail=f"Order {order_id} not found")
    return {
        "status": "success",
        "data": {
            "order_id": order_id,
            "delivery_status": "Delivered",
            "delivered_at": datetime.now(timezone.utc).isoformat(),
            "message": "Genesis Crystals have been re-issued to the player's account.",
        },
    }


@app.post("/api/refunds", tags=["Top-Up and Refund"])
async def initiate_refund(body: RefundRequest):
    """Open a refund ticket. Minor accounts require guardian verification before approval."""
    _, order = _case_insensitive_lookup(SEED_DATA.get("orders", {}), body.order_id)
    if order is None:
        raise HTTPException(status_code=404, detail=f"Order {body.order_id} not found")
    ticket_id = f"RFD{uuid.uuid4().hex[:10].upper()}"
    requires_guardian = bool(body.is_minor_account)
    return {
        "status": "success",
        "data": {
            "ticket_id": ticket_id,
            "order_id": body.order_id,
            "amount_usd": order.get("amount_usd"),
            "reason": body.reason,
            "requires_guardian_verification": requires_guardian,
            "expedited": requires_guardian,
            "opened_at": datetime.now(timezone.utc).isoformat(),
        },
    }


@app.post("/api/refunds/guardian_verification", tags=["Top-Up and Refund"])
async def verify_guardian(body: GuardianVerificationRequest):
    """
    Guardian verification for Minor Account refunds.
    Checks stored guardian name + child SSN last4 + payment last4 against seed record.
    """
    _, player = _case_insensitive_lookup(SEED_DATA.get("players", {}), body.uid)
    if player is None:
        raise HTTPException(status_code=404, detail=f"Player {body.uid} not found")
    if not player.get("is_minor"):
        raise HTTPException(status_code=400, detail="Account is not flagged as a minor account")

    stored_guardian = str(player.get("guardian_name") or "").strip().lower()
    stored_child_ssn = str(player.get("ssn_last4") or "")
    provided_guardian = body.guardian_name.strip().lower()

    guardian_ok = stored_guardian == provided_guardian
    child_dob_ok = bool(body.child_dob)  # The demo treats any non-empty DOB as provided
    payment_ok = bool(body.payment_last4) and len(body.payment_last4) == 4
    gov_id_ok = bool(body.gov_id_last4) and len(body.gov_id_last4) == 4

    verified = guardian_ok and child_dob_ok and payment_ok and gov_id_ok
    return {
        "status": "success",
        "data": {
            "uid": body.uid,
            "guardian_verified": verified,
            "checks": {
                "guardian_name_matches": guardian_ok,
                "child_dob_provided": child_dob_ok,
                "payment_last4_provided": payment_ok,
                "gov_id_last4_provided": gov_id_ok,
            },
            "refund_eligible": verified,
        },
    }


# ===========================================================================
# Compensation and Bugs endpoints
# ===========================================================================
@app.get("/api/incidents", tags=["Compensation and Bugs"])
async def check_known_incidents():
    """List all confirmed service incidents."""
    return {"status": "success", "data": SEED_DATA.get("incidents", [])}


@app.get("/api/incidents/affects/{uid}", tags=["Compensation and Bugs"])
async def list_affecting_incidents(uid: str):
    """List known incidents that affect the given UID based on its server region / UID prefix."""
    _, player = _case_insensitive_lookup(SEED_DATA.get("players", {}), uid)
    if player is None:
        raise HTTPException(status_code=404, detail=f"Player {uid} not found")

    region = player.get("server_region")
    matches = []
    for incident in SEED_DATA.get("incidents", []):
        affects = False
        if incident.get("region") and incident.get("region") == region:
            affects = True
        prefix = incident.get("affected_uids_starts_with")
        if prefix and str(uid).startswith(str(prefix)):
            affects = True
        if affects:
            matches.append(incident)
    return {"status": "success", "data": matches}


@app.post("/api/compensation/tickets", tags=["Compensation and Bugs"])
async def submit_compensation_ticket(body: CompensationTicketRequest):
    """Open a compensation ticket. Returns the ticket ID and standard compensation amount if applicable."""
    _, player = _case_insensitive_lookup(SEED_DATA.get("players", {}), body.uid)
    if player is None:
        raise HTTPException(status_code=404, detail=f"Player {body.uid} not found")

    standard_primogems = 0
    incident_confirmed = False
    if body.incident_id:
        for inc in SEED_DATA.get("incidents", []):
            if inc.get("incident_id", "").upper() == body.incident_id.upper():
                standard_primogems = inc.get("standard_compensation_primogems", 0)
                incident_confirmed = True
                break

    ticket_id = f"CMP{uuid.uuid4().hex[:10].upper()}"
    return {
        "status": "success",
        "data": {
            "ticket_id": ticket_id,
            "uid": body.uid,
            "incident_id": body.incident_id,
            "incident_confirmed": incident_confirmed,
            "category": body.category,
            "standard_compensation_primogems": standard_primogems,
            "goodwill_eligible": incident_confirmed,
            "status": "PendingReview",
            "opened_at": datetime.now(timezone.utc).isoformat(),
        },
    }


@app.post("/api/mail/ingame", tags=["Compensation and Bugs"])
async def issue_ingame_mail(body: IngameMailRequest):
    """Queue an in-game mail to the player, optionally with item attachments (Primogems, Fates)."""
    _, player = _case_insensitive_lookup(SEED_DATA.get("players", {}), body.uid)
    if player is None:
        raise HTTPException(status_code=404, detail=f"Player {body.uid} not found")
    mail_id = f"MSG{uuid.uuid4().hex[:10].upper()}"
    return {
        "status": "success",
        "data": {
            "mail_id": mail_id,
            "uid": body.uid,
            "subject": body.subject,
            "attachments": body.attachments or [],
            "expires_at_hours": 30 * 24,
            "delivered": True,
        },
    }
